name: Node.js CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run ESLint (auto-fix)
      run: npx eslint . --ext .js,.jsx,.ts,.tsx --fix

    - name: Run Prettier (auto-fix)
      run: npx prettier --write .

    - name: Check for changes after auto-fix
      run: |
        git diff --exit-code || echo "There are changes to be committed"

    - name: Commit and push changes (if any)
      if: success() && steps.check_changes.outputs.changed == 'true'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Auto-fix code formatting and linting issues"
        git push origin main

    - name: Run tests
      run: npm test

    - name: Upload coverage reports
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: path/to/coverage/report
